// src/app/scripts/page.tsx
"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { useBriefContext } from "@/context/BriefContext";
import { describePlatformPatternForBrief } from "@/engine/platforms";

export default function ScriptsPage() {
  const router = useRouter();
  const { activeBrief } = useBriefContext();

  const [generatedScript, setGeneratedScript] = useState<string>("");
  const [hasGenerated, setHasGenerated] = useState(false);

  // If there is no active brief, send the user back to /briefs
  useEffect(() => {
    if (!activeBrief) {
      router.replace("/briefs");
    }
  }, [activeBrief, router]);

  if (!activeBrief) {
    return (
      <div className="p-6 text-sm text-neutral-500">
        Redirecting… (No active brief selected)
      </div>
    );
  }

  /**
   * Core engine step:
   * Brief → platform-aware script skeleton.
   *
   * Uses the platform intelligence layer to describe how this
   * script should behave on TikTok / X / LinkedIn / etc, then
   * wraps it in an MVP-friendly structure.
   */
  const buildScriptFromBrief = () => {
    const lines: string[] = [];

    const {
      title,
      trend,
      objective,
      audienceHint,
      platformHint,
      formatHint,
      outcomeHint,
    } = activeBrief;

    // Header / context
    lines.push(`Script for: ${title}`);
    lines.push("");

    if (trend) {
      lines.push(
        `Trend: ${
          typeof trend === "string" ? trend : `${trend.name} (${trend.status})`
        }`
      );
    }

    if (objective) {
      lines.push(`Objective: ${objective}`);
    }

    if (audienceHint) {
      lines.push(`Audience: ${audienceHint}`);
    }

    if (platformHint) {
      lines.push(`Platform: ${platformHint}`);
    }

    if (formatHint) {
      lines.push(`Format: ${formatHint}`);
    }

    if (outcomeHint) {
      lines.push(`Desired outcome: ${outcomeHint}`);
    }

    lines.push("");
    lines.push("---");
    lines.push("");

    // Platform intelligence: narrative pattern for TikTok / X / LinkedIn / etc.
    const platformPatternLines = describePlatformPatternForBrief(activeBrief);
    lines.push(...platformPatternLines);

    lines.push("");
    lines.push("---");
    lines.push("");

    // MVP note – this is where the real models will plug in.
    lines.push(
      "// In the live Appatize engine, this pattern will be filled with concrete hooks, beats and lines generated by the cultural intelligence models."
    );

    return lines.join("\n");
  };

  const handleGenerateScript = () => {
    const script = buildScriptFromBrief();
    setGeneratedScript(script);
    setHasGenerated(true);
  };

  return (
    <div className="space-y-8">
      {/* Header */}
      <header className="space-y-1">
        <h1 className="text-2xl font-semibold tracking-tight">
          Script Generator
        </h1>
        <p className="text-sm text-neutral-400">
          Turning your brief into platform-native, creator-style scripts. This
          is the MVP view of the Appatize engine.
        </p>
      </header>

      {/* Brief summary card */}
      <section className="rounded-2xl border border-shell-border bg-shell-panel/90 p-5 shadow-ring-soft">
        <div className="flex flex-col justify-between gap-4 md:flex-row md:items-start">
          <div className="space-y-2">
            <h2 className="text-sm font-semibold text-neutral-100">
              {activeBrief.title}
            </h2>

            {activeBrief.trend && (
              <p className="text-[11px] text-neutral-400">
                Trend:{" "}
                <span className="font-medium text-neutral-100">
                  {typeof activeBrief.trend === "string"
                    ? activeBrief.trend
                    : activeBrief.trend.name}
                </span>
              </p>
            )}

            {activeBrief.objective && (
              <p className="text-[11px] text-neutral-400">
                Objective:{" "}
                <span className="font-medium text-neutral-100">
                  {activeBrief.objective}
                </span>
              </p>
            )}

            {activeBrief.audienceHint && (
              <p className="text-[11px] text-neutral-400">
                Audience:{" "}
                <span className="font-medium text-neutral-100">
                  {activeBrief.audienceHint}
                </span>
              </p>
            )}

            {activeBrief.platformHint && (
              <p className="text-[11px] text-neutral-400">
                Platform:{" "}
                <span className="font-medium text-neutral-100">
                  {activeBrief.platformHint}
                </span>
              </p>
            )}

            {activeBrief.formatHint && (
              <p className="text-[11px] text-neutral-400">
                Format:{" "}
                <span className="font-medium text-neutral-100">
                  {activeBrief.formatHint}
                </span>
              </p>
            )}
          </div>

          <div className="flex flex-col items-end gap-2 text-[11px] text-neutral-500">
            {activeBrief.status && (
              <span className="inline-flex items-center rounded-full bg-black/40 px-2 py-0.5 text-[10px] font-medium text-neutral-300">
                {activeBrief.status}
              </span>
            )}
            {activeBrief.createdAt && (
              <span>
                {new Date(activeBrief.createdAt).toLocaleDateString()}
              </span>
            )}
          </div>
        </div>

        {/* Actions */}
        <div className="mt-4 flex flex-wrap items-center gap-2">
          <button
            type="button"
            onClick={handleGenerateScript}
            className="inline-flex items-center gap-1 rounded-pill bg-brand-pink px-4 py-2 text-[11px] font-semibold text-black transition-colors hover:bg-brand-pink-soft"
          >
            {hasGenerated ? "Regenerate script" : "Generate script"}
            <span className="text-xs">⚡</span>
          </button>

          <button
            type="button"
            onClick={() => router.push("/briefs")}
            className="inline-flex items-center gap-1 rounded-pill border border-shell-border bg-black/20 px-3 py-2 text-[11px] font-medium text-neutral-200 transition-colors hover:border-brand-pink/40 hover:bg-black/40"
          >
            Back to briefs
          </button>
        </div>
      </section>

      {/* Generated script editor */}
      <section className="space-y-2">
        <div className="flex items-center justify-between">
          <h2 className="text-sm font-medium text-neutral-100">
            Script draft
          </h2>
          <p className="text-[11px] text-neutral-500">
            You can edit this draft manually after generation.
          </p>
        </div>

        <div className="rounded-2xl border border-shell-border bg-shell-panel/90 p-4 shadow-ring-soft">
          <textarea
            value={generatedScript}
            onChange={(e) => setGeneratedScript(e.target.value)}
            placeholder="Click &quot;Generate script&quot; to create a first draft based on your brief..."
            className="h-64 w-full resize-y border-none bg-transparent text-xs text-neutral-100 outline-none focus:ring-0"
          />
        </div>
      </section>
    </div>
  );
}
